# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-11 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryInfo11',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=255)),
            ],
        ),
    ]
